apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elasticsearch-perl
spec:
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: Elasticsearch Perl Client
      name: elasticsearch-perl
    spec:
      repository: elastic/elasticsearch-perl
      teams:
        devtools-team: {}
        everyone:
          access_level: READ_ONLY
  owner: group:devtools-team
  type: buildkite-pipeline
