= Building/Testing the Packages

There are three packages in this repo: `Search-Elasticsearch` (= the main
package), `Search-Elasticsearch-Async`, and `Search-Elasticsearch-Cxn-NetCurl`

The +dist.ini+ for each package is located in the `dist/`, `dist-async/` and
`dist-netcurl/` sub-directories. Please ignore the `dist.ini` at the root
directory.

In order to build or test the distributions all you have to do is cd into the
relevant directory and run the dzil (see http://dzil.org/[Dist::Zilla])
commands from there. E.g: `dzil test`.

=== SYNOPSIS

[source,bash]
....
# install Dist::Zilla
cpanm Dist::Zilla

# cd into dist/ dist-async/ or dist-netcurl/
cd dist

# install developer requirements
dzil --authordeps --missing | cpanm

# if ReadmeFromPod doesn't install cleanly, pin it to version 0.21:
cpanm Dist::Zilla::Plugin::ReadmeFromPod@0.21 Test::Pod

# install build requirements:
dzil --listdeps --missing | cpanm

# run tests w/o Elasticsearch
dzil test --all

# manually run an Elasticsearch cluster
elasticsearch &

# run tests against a running Elasticsearch with the ES environment variable
ES=localhost:9200 dzil test --all
....

= Contributing to elasticsearch-perl

If you have a bugfix or new feature that you would like to contribute to
Elasticsearch.pm, please find or open an issue about it first. Talk about
what you would like to do. It may be that somebody is already working on
it, or that there are particular issues that you should know about before
implementing the change.

We enjoy working with contributors to get their code accepted. There are
many approaches to fixing a problem and it is important to find the best
approach before writing too much code.

The process for contributing to any of the Elasticsearch repositories is
similar.

1. *Sign the contributor license agreement*
+
Please make sure you have signed the
http://www.elastic.co/contributor-agreement/[Contributor License Agreement].
We are not asking you to assign copyright to us, but to give us the right to
distribute your code without restriction. We ask this of all contributors in
order to assure our users of the origin and continuing existence of the code.
You only need to sign the CLA once.

2. *Test*
+
Run the full test suite and ensure it completes without errors with your
changes.

3. *Rebase your changes*
+
Update your local repository with the most recent code from the main
`elasticsearch-perl` repository, and rebase your branch on top of the latest
master branch. We prefer your changes to be squashed into a single commit.

4. *Submit a pull request*
+
Push your local changes to your forked copy of the repository and
submit a pull request. In the pull request, describe what your changes
do and mention the number of the issue where discussion has taken place,
eg ``Closes #123''.

Then sit back and wait. There will probably be discussion about the
pull request and, if any changes are needed, we would love to work
with you to get your pull request merged into Search::Elasticsearch.
