steps:
  - label: ":elasticsearch: :dromedary_camel: ES Perl ({{ matrix.perl }}) Test Suite: {{ matrix.suite }}"
    agents:
      provider: "gcp"
    env:
      PERL_VERSION: "{{ matrix.perl }}"
      TEST_SUITE: "{{ matrix.suite }}"
      STACK_VERSION: 8.12-SNAPSHOT
      CLIENT_VER: "8_0"
      PERL_HTTP_TINY_SSL_INSECURE_BY_DEFAULT: 1
    matrix:
      setup:
        suite:
          - "free"
          - "platinum"
        perl:
          - "5.38"
          - "5.36"
          - "5.34"
    command: ./.buildkite/run-tests
    artifact_paths: "*.xml"
