#!/usr/bin/env bash
#
# Version 1.1
# - Moved to .ci folder and seperated out `run-repository.sh`
# - Add `$RUNSCRIPTS` env var for running Elasticsearch dependent products
script_path=$(dirname $(realpath -s $0))
source $script_path/functions/imports.sh
set -euo pipefail

echo "--- Start Elasticsearch [$STACK_VERSION container]"
DETACH=true bash $script_path/run-elasticsearch.sh

if [[ -n "$RUNSCRIPTS" ]]; then
  for RUNSCRIPT in ${RUNSCRIPTS//,/ } ; do
    echo "--- Running run-$RUNSCRIPT.sh"
    CONTAINER_NAME=${RUNSCRIPT} \
      DETACH=true \
      bash $script_path/run-${RUNSCRIPT}.sh
  done
fi

bash $script_path/run-repository.sh
